### ISSUE TITLE
Bug with combination '*[any number]*'

### ISSUE THREAD

**Issue by Lol9tor** [borgar/textile-js#28]
If in textile format you write combination as like this:  <pre> \*[2015]\* </pre> you get not correct html. If anywhere in the text i want to do bold number in [ ] i get something in footnotes. I think it's bug.

**Comment by borgar** [comment]
This is interesting none of the implementations agree on what to do here:

With the input `*[2015]*` this is what happens:

[PHP flavour](http://txstyle.org/doc) does this:

    <p><strong>[2015]</strong></p>

[RedCloth](http://redcloth.org/) does this:

    <p><strong><sup class="footnote" id="fnr2015"><a href="#fn2015">2015</a></sup></strong></p>

TxJS does this:

    <p>*<sup class="footnote" id="fnr2015"><a href="#fn2015">2015</a></sup>*</p>

TxJS is obviously the worst here. According to the docs/spec what *should* happen is what RedCloth does; a bold footnote. But I agree that the most useful thing to happen here is what the PHP variation does.

It's not clear to me at this point why the PHP implementation doesn't generate a footnote, but if the reasoning is good I'll most likely want to follow the PHP version here.

**Comment by Lol9tor** [comment]
this code <pre>\*[2015]\* </pre>  should transform to <pre>`<p><strong><sup class="footnote" id="fnr2015"><a href="#fn2015">2015</a></sup></strong></p>`</pre> only if after ' ] ' char we have '.' dot char. On http://redcloth.org/hobix.com/textile/ we have example. 

However in other cases it should transform just like bold expression `<p><strong>[2015]</strong></p>`

**Comment by borgar** [comment]
I have investigated this and it turns out that PHP variant has a simple RegExp syntax for footnotes: `/(?<=\S)\[(\d+?)(\!?)\]\s?/g`

This means that they must be one or more numbers, surrounded by square brackets, which immediately follow a non-whitespace character.

The catch is that any opening span tag generated by php-tx inserts a temporary space into text which prevents a match by the footnote. So footnotes can never follow an opening tag. This is a bit weird especially considering that `<b>[1234]</b>` *does* get converted to a footnote. But this is what happens when you define a context sensitive syntax and then try to sidestep context when interpreting it.

Anyway, there are several problems causing the misbehaviour here:

1. Footnotes are missing the "follow a non-whitespace" rule.

2. `*[1234]*` is failing to parse a bold phrase because `[1234]` is being processed as a language and Textile has a rule against empty phrases.

   I'd love to restrict the language tag to allow only [BCP 47](http://www.ietf.org/rfc/bcp/bcp47.txt) valid tags. I suspect that will break things for users trying to be clever, so I'm resisting the urge.

While I'm at this I think I'll add the missing feature of suppressing the link with a trailing `!`.
