### ISSUE TITLE
Numbered lists are not correctly rendered

### ISSUE THREAD

**Issue by davidtrattnig** [borgar/textile-js#30]
Numbered lists using the hash sign ('#'), are not rendered as numbered lists but as plain hashes, e.g.:

\# First
\# Second
\# Third

but should be

1. First
2. Second
3. Third

**Comment by davidtrattnig** [comment]
I got that case working with following textile library: https://github.com/alexyoung/stextile

**Comment by borgar** [comment]
My tests indicate that they do work. So there must be something more to this. Can you provide more details or a test case?

**Comment by kpym** [comment]
I think that this happens when there is no paragraph separation before the list. Like in this case : 
~~~~~~~~
Some text
# One
# Two
~~~~~~~~
that is compiled to 
~~~~~~~~
<p>Some text<br />
# One<br />
# Two</p>
~~~~~~~~
In other parsers this is not considered as single paragraph and a new list is started. 
This is probably a question of convention, but in any case this is not consistent with the way line break is treated inside a list, IMO.
What I mean by this is the following :
 
1. If we have a line break inside paragraph : `<br />` is inserted but no new paragraph is created.
    This behavior is consistent with the previous case. 
2. If we have a line break inside a list item a new paragraph is created and the following lines are not transformed to list items: 
~~~~~~~~
# One
Some text
# Two
~~~~~~~~
is compiled to : 
~~~~~~~~
<ol>
	<li>One</li>
</ol>
<p>Some text<br />
# Two</p> 
~~~~~~~~

I think that probably the best is the inverse behavior : 

* line starting with # should be considered as list item even if the previous line is not empty.
* line break inside list item should not interrupt the list by introducing new paragraph.

**Comment by borgar** [comment]
@kpym Yep, I think you nailed it. I remembered as I read your comment that [this has come up before and I had rejected it](https://github.com/borgar/textile-js/issues/18) on the basis that it was unhealthy for the syntax to allow ambiguity between block-level and inline-level markup.

I think I'll have to give in to this and fix it because it's obviously what users expect, and besides, there are more problems with list parsing.

My new line of reasoning:

Firstly, both RedCloth and PHP are consistent in that lists immediatly following a linebreak should be rendered as lists (if their rendering does not agree). I do care about compatibility.

Secondly, in PHP it is possible to embed lists within block-level tags, so stuff like this works:

    bq. Quote with an embedded list
    * Item 1
    * Item 2

And is different from:

    bq. Quote with a list following
    
    * Item 1
    * Item 2

Personally, I think the former should be written:

    bq.. Quote with a list following
    
    * Item 1
    * Item 2

That is what the double-period is for, but if everyone else agrees that this is the standard now, then I suppose I'll have to accept that.


Thirdly, as pointed out there are shortcommings in the list parser. The above example of:

    # One
    Some text
    # Two

Should render to:

    <ol>
        <li>One<br />
        Some text</li>
        <li>Two</li>
    </ol>

**Comment by kpym** [comment]
I don't know if I have to put this in a new Issue, but as it is always about lists and how they starts, I put it here.

~~~~~~~
* uno
* dos
# one
~~~~~~~

produce

~~~~~~~
<ul>
	<li>uno</li>
	<li>dos</li>
	<li>one</li>
</ul>
~~~~~~~

What we expect in this case is 

~~~~~~~
<ul>
	<li>uno</li>
	<li>dos</li>
</ul>
<ol>
	<li>one</li>
</ol>
~~~~~~~

**Comment by borgar** [comment]
Probably should have been a separate ticket but let's keep it here for now. Thing is: RedCloth does the same thing we do here, and PHP does something way crazier; it nests the "one" item inside the "dos" item. I guess this is consistent with the line-break handling above, but it feels messy.

I don't want to introduce the *third* behaviour here so I think I might stay with the current behaviour. I'll have to look at the code though before I determine what to do. I want to support [2.2 enhanced lists](http://txstyle.org/article/37/enhanced-lists) which may affect this.

**Comment by borgar** [comment]
I'm documenting my reasoning on the mixed lists issue in ticket #33.
