### ISSUE TITLE
jira mode .. 

### ISSUE THREAD

**Issue by jmls** [borgar/textile-js#46]
Is there any addon, utility that can parse the jira textile mode (they have some differences) 

or does anyone know of a library that can convert jira textile to html ?

**Comment by borgar** [comment]
I am not aware of anything that can convert the Jira syntax other than Jira itself. 

The syntax is much easier to parse than Textile because it doesn't include any of the things that make Textile complicated. These being: Mixing in HTML freely, multiline blocks, element attributes.

The syntax might kind-of depend on Jira/Confluence for things like macros and issue/user information and it will be hard to try to create unit-tests without an open reference implementation to experiment with.

However, I'm willing to examine this further because this seems quite easy to do compared to full-blown Textile.

**Comment by borgar** [comment]
I have examined this and the verdict is that even though Jira syntax shares some similarities with markdown, these are all completely superficial. While a Jira parser is something that I would be willing to spend time on, it has little to do with this project.
