### ISSUE TITLE
Please support nested list

### ISSUE THREAD

**Issue by kceiw** [borgar/textile-js#47]
I have a content in this format
```
* unsorted list item 1
#    sorted list item 1
#    sorted list item 2
```

It cannot handle the sorted list property when I convert it to html.
What I got is

```
<ul>
	<li>unsorted list item 1<br />
#    sorted list item 1<br />
#    sorted list item 2</li>
</ul>
```

It'd be nice if it generates
```
<ul>
	<li>unsorted list item 1</li>
        <ol>
            <li>sorted list item 1</li>
            <li>sorted list item 2</li>
        <ol>
</ul>
```

**Comment by borgar** [comment]
I can and will fix this whitespace parsing problem. But the parser should never emit the markup you suggest because it is not valid HTML.

If you want this:

```
<ul>
	<li>unsorted list item 1
	<ol>
		<li>sorted list item 1</li>
		<li>sorted list item 2</li>
	<ol></li>
</ul>
```

Then the correct way of writing that is:

```
* unsorted list item 1
## sorted list item 1
## sorted list item 2
```
In Textile, indentation level is determined by the number of list symbols (`*` or `#`). The list type is determined by the last symbol of any new indentation level. So what this should render to is:

```
<ul>
	<li>unsorted list item 1</li>
	<li>sorted list item 1</li>
	<li>sorted list item 2</li>
</ul>
```
This is what [Redcloth](http://redcloth.org/) does and I believe them to be correct.

The PHP implementation does do what you post here but I think that is a bug. Firstly, they don't emit incorrectly nested list-HTML in other cases. Secondly, they only support the indentation shift for the first change of symbol:

<table>
<tr><th>Textile markup input</th><th>PHP-textile HTML output</th></tr>
<tr><td>
<pre>
# OL
# OL
* UL
* UL
# OL
# OL
* UL
* UL
</pre>
</td><td>
<pre>
&lt;ol>
	&lt;li>OL&lt;/li>
	&lt;li>OL&lt;/li>
&lt;ul>
	&lt;li>UL&lt;/li>
	&lt;li>UL&lt;/li>
	&lt;li>OL&lt;/li>
	&lt;li>OL&lt;/li>
	&lt;li>UL&lt;/li>
	&lt;li>UL&lt;/li>
&lt;/ul>
&lt;/ol>
</pre>
</td></tr></table>

So I'm pretty sure this isn't intended behaviour.

**Comment by kceiw** [comment]
Thanks for the explanation. I'm using some kind of ruby web application and it converts it the way I expect. That's why I thought this is a bug.
Since that's not a valid HTML, I'm ok to just close the bug then.
