### ISSUE TITLE
Tags such as <notextile> are ignored

### ISSUE THREAD

**Issue by hiro42** [borgar/textile-js#49]
Tags like:

`<notextile>*.Catalog und *.*</notextile>`

Are ignored by textile.js. It is interpreted correctly on [txstyle.org](https://txstyle.org/) sandbox though. Those tags appear to be unsupported by textile.js

**Comment by borgar** [comment]
`<notextile>` is supported, but only on block level. Which means that the test case given does render correctly. What will fail is this:

    pre <notextile>*.Catalog und *.*</notextile> post

It should yield:

    <p>pre *.Catalog und *.* post</p>

But wrongly emits:

    <p>pre <strong>.Catalog und *.</strong> post</p>

**Comment by borgar** [comment]
Looked at this a bit and it turns out to be a pretty stupid bug hidden by not having a good test for this. `notextile` tags are accounted for, but [then just parsed as if they were textile](https://github.com/borgar/textile-js/blob/master/src/textile/phrase.js#L168). 🙄  

This is is very simple to fix. I will upload an update asap.
