### ISSUE TITLE
Bug with missing whitespace or newlines in tables and lists

### ISSUE THREAD

**Issue by level420** [borgar/textile-js#58]
I'm using the fresh released version 2.0.5 👍 

In trying to convert redmine textile with textile.js.
I've observed that textile.js needs whitespace/newlines where e.g. https://textile-lang.com/ doesn't.

The following textile code:
```textile
* [*H*]attric: *DO*
|*D*|Diversity|
|*O*|Obstacles|
```
should result in a `ul` having a single `li` , and a `table` with two lines belonging to that `li`.

In textile.js this results in following html code (`<p>` ommitted)
```html
<ul>
	<li><strong>H</strong>attric: <strong>DO</strong><br>
|*D*|Diversity|<br>
|*O*|Obstacles|</li>
</ul>
```
where on https://textile-lang.com/ it results as follows (I think correctly) 
```html
<ul>
	<li><strong>H</strong>attric: <strong>DO</strong><br />
<table>
		<tr>
			<td><strong>D</strong></td>
			<td>Diversity</td>
		</tr>
		<tr>
			<td><strong>O</strong></td>
			<td>Obstacles</td>
		</tr><br />
</table></li>
</ul>
```
Table rendering starts working, if there is a newline after the first line (`[*H*]attric: *DO*`), but then the table does not belong to the `li` element, but is rendered after the closing `ul`.

**Comment by level420** [comment]
Note that if a tables line has whitespace in front, not table is rendered:
```textile
 |D|Diversity|
 |O|Obstacles|
```
results in
```html
|D|Diversity| |O|Obstacles|
```

**Comment by level420** [comment]
I'm considering this to be a bug

**Comment by borgar** [comment]
Firstly, for your specific case: RedMine uses [RedCloth](http://redcloth.org/) as its converter which emits exactly the same thing that textile-js does given your input. If you are looking for 1-to-1 conversion, then I don't get why you would want something different.

Secondly, this is not a bug. The PHP implementation is in error here. What textile-lang is doing is not valid textile conversion. Tables and lists are both are block level and must not be nested in each other. The fact that this example works in the PHP version is because they don't actually parse or validate the source but simply regexp replace things with little regard to context. This isn't how textile-js or RedCloth work.

The textile language allows mixing HTML and shorthand for this very reason: Because complex needs exist. The correct way to get the result you want is to mix in some HTML:

```html
<ul>
<li>[*H*]attric: *DO*

|*D*|Diversity|
|*O*|Obstacles|

</li>
</ul>
```

---

Btw, the PHP implementation is quite bonkers. You can do all sorts of absurd things in it that we won't accept. Here is an example:

```textile
p. foo
* bar
```

Which this version renders: 

```html
<p>foo</p>
<ul>
	<li>bar</li>
</ul>
```

Whereas they emit invalid HTML with a list nested in a paragraph and throw a bunch of \<br>s in there, because why not?

```html
<p>foo<br />
<ul>
	<li>bar</li><br />
</ul></p>
```

**Comment by level420** [comment]
@borgar you're right that RedCloth is compatible to textile.js. Obviously someone at redmine tweaked the RedCloth implementation textile parse to allow the construct above to work, e.g. allow tables within list elements. Tested here with current redmine version.

One solution for me would be to allow the following to work:
```html
<ul>
<li><strong>H</strong>attric: <strong>DO</strong><br />
|*D*|Diversity|</li>
</ul>
```
which is the primary output of running `textile("* [*H*]attric: *DO*\r\n|*D*|Diversity|")` and simple take the output from the first run and feed it again into textile.

The problem here is, that textile.js needs a `\r\n` in front of the first table line.

Could this be accomplished in a simple way?

**Comment by borgar** [comment]
Yeah, I see the problem. I'm not sure a second passthrough will be safe, there are likely cases, esp. with \<notextile> where context is lost and things go strange.

For custom markup you really need a custom parser. My recommendation would be to fork the project, add support for inline tables and build your own package.

I have created a branch where your desired case works: https://github.com/borgar/textile-js/compare/inline-tables

I can't vouch for what happens if the branch finds something it thinks is a table elsewhere. And you will have to build and package this yourself. If you are just running a local job using `npm link` might spare you some work on that front.

**Comment by level420** [comment]
Thank you @borgar ! Your help is very appreciated. I'll give it a try.

**Comment by level420** [comment]
@borgar Cool! works like expected for our use case!
I'm afraid to ask, but could you please, please release at npm? 
It seems that the new inline table feature is only active when setting the option ` { inlineTables : true }` so it should not do any harm to others having this published.
That would be great!

**Comment by borgar** [comment]
Sorry, releasing it also means supporting it. This is not something I am willing to release without more work and _way_ more tests.

**Comment by level420** [comment]
I understand that. But the branch already helps us a lot.
But maybe as time passes you get back to this (I hope so!) and this feature find its way into the master branch. :-)
