### ISSUE TITLE
Why does the `textile.jsonml` function prepend the syntax tree with an `"html"` node?

### ISSUE THREAD

**Issue by craigkovatch** [borgar/textile-js#67]
Output then looks something like `["html", ["p", "hello world"]]`, which represents an HTML tree like

```
<html>
  <p>hello world</p>
</html>
```

But this isn't valid HTML, you'd need a `<head>` tag and a `<body>` tag to contain all the other parse results. This is easy enough to correct by calling `shift()` on the output array, but I'm curious to understand why it prepends this `html` container in the first place.

**Comment by borgar** [comment]
JsonML has the limitation that it requires a single root node as a container†. Textile syntax, however, is not limited in this way.

Consider this Textile markup:

```textile
h1. heading

p. paragraph
```

Which should really translate to:

```json
[ "h1", "heading" ],
[ "p", "paragraph" ]
```

But since the root needs to be a valid element, all the "block level" textile elements are wrapped in a container tag:

```json
[ "html",
  [ "h1", "heading" ],
  [ "p", "paragraph" ]
]
```

The selection of `html` is completely arbitrary. Textile-js ignores this internally so there might be a case for changing it to something like a `div` to remove processing work for anyone using the `.jsonml()` function.

---

† At least, it was that way back when I originally wrote the library.

**Comment by craigkovatch** [comment]
Thanks for the explanation!
